<a href="https://colab.research.google.com/github/jimisherg/material-ui/blob/master/Natural_Laguage_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from nltk import pos_tag
nltk.download('averaged_perceptron_tagger')
p = pos_tag(y)
print(p)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


[('Always', 'NNS'), ('check', 'VBP'), ('tumhara', 'JJ'), ('actual', 'JJ'), ('usage', 'NN'), ('to', 'TO'), ('avoid', 'VB'), ('unexpected', 'JJ'), ('charges', 'NNS'), ('.', '.')]


**Text PreProcessing**

In [ ]:
text = (
    "Natural language processing (NLP) is an interdisciplinary subfield of computer science and artificial intelligence. "
    "It is primarily concerned with providing computers with the ability to process data encoded in natural language. "
    "Thus, it is closely related to information retrieval, knowledge representation, and computational linguistics, a subfield of linguistics. "
    "Typically, data is collected in text corpora using either rule-based, statistical, or neural-based approaches in machine learning and deep learning."
)

print(text)


Natural language processing (NLP) is an interdisciplinary subfield of computer science and artificial intelligence. It is primarily concerned with providing computers with the ability to process data encoded in natural language. Thus, it is closely related to information retrieval, knowledge representation, and computational linguistics, a subfield of linguistics. Typically, data is collected in text corpora using either rule-based, statistical, or neural-based approaches in machine learning and deep learning.


In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize
sent = sent_tokenize(text)
print(sent)

['Natural language processing (NLP) is an interdisciplinary subfield of computer science and artificial intelligence.', 'It is primarily concerned with providing computers with the ability to process data encoded in natural language.', 'Thus, it is closely related to information retrieval, knowledge representation, and computational linguistics, a subfield of linguistics.', 'Typically, data is collected in text corpora using either rule-based, statistical, or neural-based approaches in machine learning and deep learning.']


['Natural', 'language', 'processing', '(', 'NLP', ')', 'is', 'an', 'interdisciplinary', 'subfield', 'of', 'computer', 'science', 'and', 'artificial', 'intelligence', '.']

['It', 'is', 'primarily', 'concerned', 'with', 'providing', 'computers', 'with', 'the', 'ability', 'to', 'process', 'data', 'encoded', 'in', 'natural', 'language', '.']

['Thus', ',', 'it', 'is', 'closely', 'related', 'to', 'information', 'retrieval', ',', 'knowledge', 'representation', ',', 'and', 'computational', 'linguistics', ',', 'a', 'subfield', 'of', 'linguistics', '.']

['Typically', ',', 'data', 'is', 'collected', 'in', 'text', 'corpora', 'using', 'either', 'rule-based', ',', 'statistical', ',', 'or', 'neural-based', 'approaches', 'in', 'machine', 'learning', 'and', 'deep', 'learning', '.']



In [ ]:
word = word_tokenize(text)
print(word)

['Natural', 'language', 'processing', '(', 'NLP', ')', 'is', 'an', 'interdisciplinary', 'subfield', 'of', 'computer', 'science', 'and', 'artificial', 'intelligence', '.', 'It', 'is', 'primarily', 'concerned', 'with', 'providing', 'computers', 'with', 'the', 'ability', 'to', 'process', 'data', 'encoded', 'in', 'natural', 'language', '.', 'Thus', ',', 'it', 'is', 'closely', 'related', 'to', 'information', 'retrieval', ',', 'knowledge', 'representation', ',', 'and', 'computational', 'linguistics', ',', 'a', 'subfield', 'of', 'linguistics', '.', 'Typically', ',', 'data', 'is', 'collected', 'in', 'text', 'corpora', 'using', 'either', 'rule-based', ',', 'statistical', ',', 'or', 'neural-based', 'approaches', 'in', 'machine', 'learning', 'and', 'deep', 'learning', '.']


In [ ]:
import random

# Sample responses for different inputs
responses = {
    "hello": ["Hello! How are you?", "Hi there! Nice to meet you!", "Greetings! How can I help you?"],
    "how are you": ["I'm fine, thank you!", "Doing well, how about you?", "Great! What about you?"],
    "nice to meet you": ["Nice to meet you too!", "Pleasure to meet you!", "Happy to meet you!"],
}

# Function to generate response
def generate_response(user_input):
    # Normalize input
    normalized_input = user_input.lower().strip()

    # Check for responses
    for key in responses:
        if key in normalized_input:
            return random.choice(responses[key])

    return "I'm sorry, I didn't understand that."

# User input
user_input = input("Aap kaise hain? ")  # You can input any sentence here
response = generate_response(user_input)
print(response)


Aap kaise hain? theek hu
I'm sorry, I didn't understand that.


In [ ]:
var = "An HTML element is a type of HTML (HyperText Markup Language) document component, one of several types of HTML nodes (there are also text nodes, comment nodes and others).[vague] The first used version of HTML was written by Tim Berners-Lee in 1993 and there have since been many versions of HTML. The current de facto standard is governed by the industry group WHATWG and is known as the HTML Living Standard.";
print(var)

An HTML element is a type of HTML (HyperText Markup Language) document component, one of several types of HTML nodes (there are also text nodes, comment nodes and others).[vague] The first used version of HTML was written by Tim Berners-Lee in 1993 and there have since been many versions of HTML. The current de facto standard is governed by the industry group WHATWG and is known as the HTML Living Standard.


In [ ]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
stop

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop = stopwords.words('english')
stop

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
from nltk.corpus import stopwords
from string import punctuation

stop = stopwords.words('english')
list(punctuation)


['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [ ]:
from nltk.corpus import stopwords
from string import punctuation

stop = stopwords.words('english')
stopwords = list(punctuation) + stop

In [ ]:
for i in var:
  if i not in stopwords:
    print(i)

A
n
 
H
T
M
L
 
e
l
e
e
n
 
 
 
p
e
 
f
 
H
T
M
L
 
H
p
e
r
T
e
x
 
M
r
k
u
p
 
L
n
g
u
g
e
 
c
u
e
n
 
c
p
n
e
n
 
n
e
 
f
 
e
v
e
r
l
 
p
e
 
f
 
H
T
M
L
 
n
e
 
h
e
r
e
 
r
e
 
l
 
e
x
 
n
e
 
c
e
n
 
n
e
 
n
 
h
e
r
v
g
u
e
 
T
h
e
 
f
r
 
u
e
 
v
e
r
n
 
f
 
H
T
M
L
 
w
 
w
r
e
n
 
b
 
T
 
B
e
r
n
e
r
L
e
e
 
n
 
1
9
9
3
 
n
 
h
e
r
e
 
h
v
e
 
n
c
e
 
b
e
e
n
 
n
 
v
e
r
n
 
f
 
H
T
M
L
 
T
h
e
 
c
u
r
r
e
n
 
e
 
f
c
 
n
r
 
 
g
v
e
r
n
e
 
b
 
h
e
 
n
u
r
 
g
r
u
p
 
W
H
A
T
W
G
 
n
 
 
k
n
w
n
 
 
h
e
 
H
T
M
L
 
L
v
n
g
 
S
n
r


In [ ]:
from nltk.tokenize import word_tokenize
var_new =  word_tokenize(var)


In [ ]:
for i in var:
  if i not in var_new:
    print(i)

A
n
 
H
T
M
L
 
e
l
e
m
e
n
t
 
i
s
 
 
t
y
p
e
 
o
f
 
H
T
M
L
 
H
y
p
e
r
T
e
x
t
 
M
r
k
u
p
 
L
n
g
u
g
e
 
d
o
c
u
m
e
n
t
 
c
o
m
p
o
n
e
n
t
 
o
n
e
 
o
f
 
s
e
v
e
r
l
 
t
y
p
e
s
 
o
f
 
H
T
M
L
 
n
o
d
e
s
 
t
h
e
r
e
 
r
e
 
l
s
o
 
t
e
x
t
 
n
o
d
e
s
 
c
o
m
m
e
n
t
 
n
o
d
e
s
 
n
d
 
o
t
h
e
r
s
v
g
u
e
 
T
h
e
 
f
i
r
s
t
 
u
s
e
d
 
v
e
r
s
i
o
n
 
o
f
 
H
T
M
L
 
w
s
 
w
r
i
t
t
e
n
 
b
y
 
T
i
m
 
B
e
r
n
e
r
s
-
L
e
e
 
i
n
 
1
9
9
3
 
n
d
 
t
h
e
r
e
 
h
v
e
 
s
i
n
c
e
 
b
e
e
n
 
m
n
y
 
v
e
r
s
i
o
n
s
 
o
f
 
H
T
M
L
 
T
h
e
 
c
u
r
r
e
n
t
 
d
e
 
f
c
t
o
 
s
t
n
d
r
d
 
i
s
 
g
o
v
e
r
n
e
d
 
b
y
 
t
h
e
 
i
n
d
u
s
t
r
y
 
g
r
o
u
p
 
W
H
A
T
W
G
 
n
d
 
i
s
 
k
n
o
w
n
 
s
 
t
h
e
 
H
T
M
L
 
L
i
v
i
n
g
 
S
t
n
d
r
d


In [ ]:
from nltk.corpus import stopwords
from string import punctuation
from nltk.tokenize import word_tokenize

# Sample input string
var = "An HTML element is a type of HTML (HyperText Markup Language) document component, one of several types of HTML nodes (there are also text nodes, comment nodes and others).[vague] The first used version of HTML was written by Tim Berners-Lee in 1993 and there have since been many versions of HTML. The current de facto standard is governed by the industry group WHATWG and is known as the HTML Living Standard."

# Download stopwords if you haven't already
import nltk
nltk.download('stopwords')
nltk.download('punkt')

# Get stopwords and punctuation
stop = stopwords.words('english')
stopwords_combined = list(punctuation) + stop

# Tokenize the input string
var_new = word_tokenize(var)

# Filter and print words that are not in the stopwords_combined
for i in var_new:
    if i.lower() not in stopwords_combined:
        print(type(i))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
from nltk.stem import LancasterStemmer,RegexpStemmer,SnowballStemmer,PorterStemmer
L = LancasterStemmer()
R = RegexpStemmer('ing');
P = PorterStemmer()
S = SnowballStemmer('english')
L.stem('changed')


'chang'

In [ ]:
R.stem('changed')

'changed'

In [ ]:
P = PorterStemmer()
P.stem('changed')

'chang'

In [ ]:
S = SnowballStemmer('english')
S.stem('changing')

`**Leminitization**`

Lemmatization is the process of reducing a word to its base or root form, which is known as a "lemma." Unlike stemming, which simply chops off prefixes or suffixes, lemmatization takes into account the meaning of the word and its context, resulting in a valid word.

Example:
The lemma of "running" is "run."
The lemma of "better" is "good."
Using NLTK for Lemmatization
Here's how you can perform lemmatization using NLTK:

python
Copy code
from nltk.stem import WordNetLemmatizer
import nltk

# Download WordNet if you haven't already
nltk.download('wordnet')

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Sample words
words = ["running", "ran", "better", "mice", "geese", "children"]

# Lemmatize each word
lemmatized_words = [lemmatizer.lemmatize(word) for word in words]

# Print the results
print(lemmatized_words)
Explanation:
WordNetLemmatizer: This class provides the lemmatization functionality.
Lemmatization Process: You can apply the lemmatize method on each word to convert it to its lemma.
Notes:
Lemmatization may require specifying the part of speech (POS) for more accurate results. By default, it assumes nouns. For example:
python
Copy code
lemmatizer.lemmatize("better", pos='a')  # 'a' for adjective
Make sure to explore how the context of the word can affect its lemma for more advanced applications!



In [ ]:
from nltk.stem import WordNetLemmatizer
import nltk

# Download WordNet if you haven't already
nltk.download('wordnet')

# Initialize the lemmatizer
wl = WordNetLemmatizer()

# Lemmatize some valid words
print(wl.lemmatize("mice"))  # Output: 'mouse'
print(wl.lemmatize("better", pos='a'))  # Output: 'good'


mouse
good


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
text = "I am Anmol Mahajan  I am a lrarning lover to thionks as rel;ated to computer  I Like kulcha chola  hello i am common man"
from nltk.tokenize import word_tokenize
word = word_tokenize(text)
print(word)

['I', 'am', 'Anmol', 'Mahajan', 'I', 'am', 'a', 'lrarning', 'lover', 'to', 'thionks', 'as', 'rel', ';', 'ated', 'to', 'computer', 'I', 'Like', 'kulcha', 'chola', 'hello', 'i', 'am', 'common', 'man']


In [ ]:
from nltk.collocations import *
B = BigramCollocationFinder.from_words(text)
B.ngram_fd

FreqDist({(' ', 'a'): 5, ('I', ' '): 3, ('a', 'm'): 3, ('m', ' '): 3, (' ', ' '): 3, ('a', ' '): 3, (' ', 't'): 3, ('o', ' '): 3, (' ', 'c'): 3, ('m', 'o'): 2, ...})

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.collocations import BigramCollocationFinder

# Your text
text = "I am Anmol Mahajan. I am a learning lover and think as related to computer. I like kulcha chola. Hello, I am a common man."

# Tokenizing the text
words = word_tokenize(text)

# Finding bigrams
bigram_finder = BigramCollocationFinder.from_words(words)

# Getting the frequency distribution of bigrams
bigrams = bigram_finder.ngram_fd.items()

# Printing the results
for bigram, freq in bigrams:
    print(f"{bigram}: {freq}")


('I', 'am'): 3
('am', 'Anmol'): 1
('Anmol', 'Mahajan'): 1
('Mahajan', '.'): 1
('.', 'I'): 2
('am', 'a'): 2
('a', 'learning'): 1
('learning', 'lover'): 1
('lover', 'and'): 1
('and', 'think'): 1
('think', 'as'): 1
('as', 'related'): 1
('related', 'to'): 1
('to', 'computer'): 1
('computer', '.'): 1
('I', 'like'): 1
('like', 'kulcha'): 1
('kulcha', 'chola'): 1
('chola', '.'): 1
('.', 'Hello'): 1
('Hello', ','): 1
(',', 'I'): 1
('a', 'common'): 1
('common', 'man'): 1
('man', '.'): 1


In [ ]:
B.ngram_fd.keys()

dict_keys([('I', ' '), (' ', 'a'), ('a', 'm'), ('m', ' '), (' ', 'A'), ('A', 'n'), ('n', 'm'), ('m', 'o'), ('o', 'l'), ('l', ' '), (' ', 'M'), ('M', 'a'), ('a', 'h'), ('h', 'a'), ('a', 'j'), ('j', 'a'), ('a', 'n'), ('n', ' '), (' ', ' '), (' ', 'I'), ('a', ' '), (' ', 'l'), ('l', 'r'), ('r', 'a'), ('a', 'r'), ('r', 'n'), ('n', 'i'), ('i', 'n'), ('n', 'g'), ('g', ' '), ('l', 'o'), ('o', 'v'), ('v', 'e'), ('e', 'r'), ('r', ' '), (' ', 't'), ('t', 'o'), ('o', ' '), ('t', 'h'), ('h', 'i'), ('i', 'o'), ('o', 'n'), ('n', 'k'), ('k', 's'), ('s', ' '), ('a', 's'), (' ', 'r'), ('r', 'e'), ('e', 'l'), ('l', ';'), (';', 'a'), ('a', 't'), ('t', 'e'), ('e', 'd'), ('d', ' '), (' ', 'c'), ('c', 'o'), ('o', 'm'), ('m', 'p'), ('p', 'u'), ('u', 't'), (' ', 'L'), ('L', 'i'), ('i', 'k'), ('k', 'e'), ('e', ' '), (' ', 'k'), ('k', 'u'), ('u', 'l'), ('l', 'c'), ('c', 'h'), ('h', 'o'), ('l', 'a'), (' ', 'h'), ('h', 'e'), ('l', 'l'), (' ', 'i'), ('i', ' '), ('m', 'm'), (' ', 'm'), ('m', 'a')])

In [ ]:
l = ["my name is Anmol Mahajan","my nbame is dhriuve"]
import pandas as pd
df = pd.DataFrame({"name":l})
df


name
0  my name is Anmol Mahajan
1       my nbame is dhriuve

In [ ]:
from sklearn.feature_extraction import CountVectorizer
cv = CountVectorizer()
new_data = cv.fit_transform(df["name"])
new_data.toarray()

ImportError: cannot import name 'CountVectorizer' from 'sklearn.feature_extraction' (/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/__init__.py)

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Example list of names (replace with your own data)
l = ["Alice", "Bob", "Alice Smith", "Charlie"]

# Create DataFrame
df = pd.DataFrame({"name": l})

# Initialize CountVectorizer
cv = CountVectorizer()

# Fit and transform the data
new_data = cv.fit_transform(df["name"])

# Convert to array
new_array = new_data.toarray()

# Print the array
print(new_array)
cv.vocabulary_


[[1 0 0 0]
 [0 1 0 0]
 [1 0 0 1]
 [0 0 1 0]]


{'alice': 0, 'bob': 1, 'smith': 3, 'charlie': 2}

In [ ]:
!pip install --upgrade scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 84.1 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.2
    Uninstalling scikit-learn-1.3.2:
      Successfully uninstalled scikit-learn-1.3.2


In [ ]:
y = "A computer mouse is a handheld input device that allows users to interact with a computer. It moves a pointer (cursor) on the screen, enabling users to select, move, and interact with text, icons, files, and other graphical user interface (GUI) elements.";
y

'A computer mouse is a handheld input device that allows users to interact with a computer. It moves a pointer (cursor) on the screen, enabling users to select, move, and interact with text, icons, files, and other graphical user interface (GUI) elements.'

In [ ]:
x = "You can reinstall or upgrade scikit-learn using pip. Run the following command in your Google Colab or local environment:";



var = "You can reinstall or upgrade scikit-learn using pip. Run the following command in your Google Colab or local environment:";

In [ ]:
from nltk.wsd import  lesk
from nltk.tokenize import word_tokenize
store  = lesk(word_tokenize(y),"mouse");
store.definition()

'a hand-operated electronic device that controls the coordinates of a cursor on your computer screen as you move it around on a pad; on the bottom of the device is a ball that rolls on the surface of the pad'